<?php
/**
 * Created by PhpStorm.
 * User: Kristóf
 * Date: 2018.11.07.
 * Time: 15:42
 */

namespace Tests\Unit\ModelTests\Eloquent;

use App\Competition;
use App\Sport;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CompetitionTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var $competition Competition
     */
    private $competition;

    /**
     * @test
     * @return void
     */
    public function competition_has_sport()
    {
        $this->setUp();
        $this->assertNotEmpty($this->competition->getCompSport());
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        // Manually creating the relationship tree.
        $user = factory(User::class)->create();
        $sport = factory(Sport::class)->create();

        $this->competition = factory(Competition::class)->create([
            'comp_promoter' => $user,
            'comp_sport' => $sport
        ]);
    }
}